Alterações e correções dos documentos
FerroEduardo/SAMU-Sistema-de-Auxilio-a-Matricula-Universitaria pull request #12
Opened 2021-08-01 19:54 UTC by romul0

tá certo?

2021-08-01 20:00 UTC, FerroEduardo requested changes

2021-08-01 23:50 UTC, FerroEduardo requested changes

2021-08-01 23:50 UTC, FerroEduardo commented on documentos/casos_de_uso.md
> +    - FA-01 - Professor não cadastrado:
Em vez de "Professor não cadastrado", seria melhor "Nenhum professor cadastrado". Da forma que está, parece que houve uma tentativa de selecionar um professor e o mesmo não estava cadastrado.

2021-08-01 23:50 UTC, FerroEduardo commented on documentos/casos_de_uso.md
> +    2.  O administrador do sistema seleciona um professor da lista (FE-01);
O FE-01 ficaria melhor no passo 4 do fluxo principal.

2021-08-01 23:50 UTC, FerroEduardo commented on documentos/casos_de_uso.md
> +    - Fluxo de exceção:
Indentação do fluxo de exceção está incorreta.

2021-08-01 23:50 UTC, FerroEduardo commented
UC11 e UC12 precisam ser discutidos

2021-08-02 00:44 UTC, romul0 commented on documentos/minimundo.md
> +Cada aluno deve ser cadastrado pela matrícula, nome, data de nascimento, endereço e curso. Cada curso tem um professor que deve ser cadastrado com seu nome, data de nascimento, endereço e curso. Além
Corrigido

2021-08-02 00:46 UTC, romul0 commented on documentos/minimundo.md
> +Cada disciplina é identificada por um controle único e pela sua descrição. Além disto, a disciplina possui um plano de aula elaborado pelo professor e a alocação da sala. Uma disciplina pode possuir
Corrigido

2021-08-02 00:48 UTC, romul0 commented on documentos/casos_de_uso.md
> +    - FA-01 - Professor não cadastrado:
Corrigido

2021-08-02 00:49 UTC, romul0 commented on documentos/casos_de_uso.md
> +    2.  O administrador do sistema seleciona um professor da lista (FE-01);
Corrigido

2021-08-02 00:49 UTC, romul0 commented on documentos/casos_de_uso.md
> +    - Fluxo de exceção:
Corrigido

2021-08-02 15:19 UTC, FerroEduardo requested changes

2021-08-02 15:19 UTC, FerroEduardo commented on documentos/casos_de_uso.md
> +    - FA-01 - Professor não cadastrado:
Você fez a troca do nome do fluxo alternativo, mas em outro caso de uso(UC03).

2021-08-02 15:43 UTC, romul0 commented on documentos/casos_de_uso.md
> +    - FA-01 - Professor não cadastrado:
Corrigido

2021-08-02 15:47 UTC, FerroEduardo reviewed
Perfeito

2021-08-05 17:04 UTC, yaansz requested changes
só dividir turma e disciplina

2021-08-05 17:04 UTC, yaansz commented on documentos/documento_de_requisitos.md
> +RF03 - O sistema deve permitir cadastrar disciplinas e turmas; (RN03)
da pra dividir isso em 2

2021-08-05 17:04 UTC, yaansz commented on documentos/casos_de_uso.md
> +    5.  O administrador do sistema seleciona as disciplinas obrigatórias e optativas da lista (FA-01);
mais fácil substituir por "ator"

2021-08-05 17:04 UTC, yaansz commented on documentos/casos_de_uso.md
> +    2.  O coordenador informa o nome e descrição da disciplina (FE-01);
ok

2021-08-05 17:07 UTC, FerroEduardo commented on documentos/casos_de_uso.md
> +    5.  O administrador do sistema seleciona as disciplinas obrigatórias e optativas da lista (FA-01);
Não faz muita diferença, mas em novos UC a gente pode fazer isso

2021-08-05 17:07 UTC, FerroEduardo commented on documentos/documento_de_requisitos.md
> +RF03 - O sistema deve permitir cadastrar disciplinas e turmas; (RN03)
Pra não dar problema com a numeração, dá pra colocar no final

2021-08-05 17:12 UTC, yaansz commented on documentos/casos_de_uso.md
> +    5.  O administrador do sistema seleciona as disciplinas obrigatórias e optativas da lista (FA-01);
sim, pq algumas alterações só foram feitas por usar o cargo e não ator, então seria bom padronizar tudo em ator em um futuro próximo

2021-08-05 18:27 UTC, VictorDigdin reviewed
Acredito que as modificações ficaram boas

2021-08-09 18:24 UTC, FerroEduardo commented on documentos/casos_de_uso.md
> +    - FE-01 - Em construção...
🤔

2021-08-09 21:06 UTC, yaansz commented
#11

2021-08-09 21:37 UTC, romul0 commented on documentos/documento_de_requisitos.md
> +RF03 - O sistema deve permitir cadastrar disciplinas e turmas; (RN03)
Feito

2021-08-09 21:37 UTC, romul0 commented on documentos/casos_de_uso.md
> +    5.  O administrador do sistema seleciona as disciplinas obrigatórias e optativas da lista (FA-01);
feito

2021-08-10 03:38 UTC, FerroEduardo approved these changes

2021-08-10 03:43 UTC, yaansz approved these changes

2021-08-10 14:32 UTC, merged